site_name: persviz
site_url: https://manavarora.github.io/persviz
repo_url: https://github.com/manavarora/persviz

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: light mode
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Theory: theory.md
  - Gallery: gallery.md
